version: "3"
services:
  db:
    image: postgres
    restart: always
    volumes:
      - gurschdata:/var/lib/postgresql/data
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: gursch
  app:
    image: antonhager/gt_backend:dev
    restart: always
    build:
      context: ./app
      dockerfile: Dockerfile
    networks:
      - webnet
    depends_on:
      - db
    environment:
      NODE_ENV: ${ENVIRONMENT:-production}
      PGPASSWORD: postgres
      PGUSER: postgres
      PGDB: gursch
      PGHOST: db
    command: ["npm", "start"]
  proxy:
    image: antonhager/gt_proxy:dev
    restart: always
    build:
      context: ./proxy
      dockerfile: Dockerfile
      args:
        CONF_PATH: ${CONF_PATH:-./proxy/prod.conf}
    depends_on:
      - app
    ports:
      - "${PORT:-80}:80"
      - "443:443"
    networks:
      - webnet
    command: ["nginx", "-g", "daemon off;"]
networks:
  ? webnet
volumes:
  ? gurschdata
