version: '3'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./gurschdata:/var/lib/postgresql/data
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: gursch
  backend-app:
    image: antonhager/gt_backend_app:0.1.2
    restart: always
    ports:
      - '1111:1337'
    networks:
      - webnet
    depends_on:
      - db
    environment:
      NODE_ENV: ${ENVIRONMENT:-production}
      PGPASSWORD: postgres
      PGUSER: postgres
      PGDB: gursch
      PGHOST: db
    command: ['npm', 'start']
networks:
  webnet:
