version: '3'
services:
  db:
    image: postgres
    restart: always
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: gursch
  backend-app:
    build: 
      dockerfile: Dockerfile-Dev
      context: .
    image: antonhager/gt_backend_app_test:latest
    networks:
      - webnet
    depends_on:
      - db
    volumes:
      - ./src:/usr/app/src
    environment:
      NODE_ENV: test
      PGPASSWORD: postgres
      PGUSER: postgres
      PGDB: gursch
      PGHOST: db
      PGPORT: 5432
networks:
  webnet:
