apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: backend-app
spec:
  selector:
    matchLabels:
      app: backend-app
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        tier: backend
        app: backend-app
    spec:
      containers:
        - name: backend-app
          image: antonhager/gt_backend_app:0.1.6
          resources:
            limits:
              cpu: 150m
            requests:
              cpu: 100m
          ports:
            - containerPort: 1337
              name: backend-app
          env:
            - name: PGHOST
              value: "10.93.128.3"
            - name: PGDATABASE
              value: gursch
            - name: PGPORT
              value: "5432"
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: backend-app
spec:
  selector:
    app: backend-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: backend-app
  type: NodePort
